---
title: Aprendizado de máquina aplicado a previsão de retornos de ativos virtuais no Mercado da Comunidade Steam
author:
    - Pedro Mendes
    - André Ricardo Oliveira da Fonseca^[Professor orientador - Centro de Matemática Computação e Cognição (CMCC/UFABC).]
documentclass: scrartcl
format: pdf
nocite: "@*"
lang: pt-BR
bibliography: references.bib
header-includes:
    - \addtokomafont{title}{\let\huge\LARGE}
---

```{=tex}
\oneHalfIndent
```

# Introdução

Este projeto se propõe a usar técnicas de aprendizado de máquina para prever o retorno de ativos virtuais no Mercado da Comunidade Steam (MCS). ^[Disponível em: <https://steamcommunity.com/market>. Acesso em: 19 nov 2023.] O MCS é um mercado virtual secundário onde usuários podem comprar e vender itens virtuais para jogos da plataforma Steam, uma loja de jogos online. O mercado é composto por itens de jogos como Counter-Strike: Global Offensive, Dota 2, Team Fortress 2, entre outros. Os itens são negociados na moeda corrente da conta utilizada e a plataforma retém 15% do valor da transação. O restante é creditado na carteira do usuário, que pode ser usado para adquirir outros itens ou jogos na plataforma. ^[Disponível em: <https://help.steampowered.com/en/faqs/view/61F0-72B7-9A18-C70B>. Acesso em: 19 nov 2023.] O preço dos ativos é determinado pela oferta e demanda dos usuários, podendo variar ao longo do tempo. A análise de mercados virtuais pode ser uma importante ferramenta para testar hipóteses econômicas, pois modelar um sistema fechado com poucas variáveis a serem analisadas permite abstrair a complexidade de mercados reais.

# Objetivos

Como objetivo geral, este trabalho planeja utilizar técnicas de aprendizado de máquina tanto para modelar o comportamento de ativos virtuais no MCS como também, para fins acadêmicos, criar um portfólio teórico lucrativo com tais informações.

Como objetivos específicos, este trabalho se propõe a:

- Realizar uma análise qualitativa das regras da plataforma, a fim de entender o funcionamento do mercado e as possíveis limitações para a coleta de dados;
- Analisar os principais ativos negociáveis por meio de estatística descritiva;
- Desenvolver um modelo estatístico que se baseie em técnicas de aprendizado de máquina;
- Medir o desempenho do modelo utilizado.

# Problema

O problema central deste projeto reside na capacidade de prever os retornos dos ativos virtuais no Mercado da Comunidade Steam (MCS) por meio de técnicas de aprendizado de máquina. O contexto inclui a investigação de padrões sazonais nos preços dos ativos, como influenciados por eventos sazonais e lançamentos de jogos, bem como a possibilidade de construir um portfólio de ativos com retornos superiores à retenção de 15% do valor da transação cobrado pela plataforma Steam.

# Hipóteses

- Hipótese 1: O uso do modelo de aprendizado de máquina Long Short Term Memory (LSTM) é adequado para predizer os rendimentos dos ativos virtuais no contexto do MCS. ^[A escolha do modelo é detalhada na seção de metodologia.]
- Hipótese 2: Existem padrões sazonais no comportamento dos preços dos ativos virtuais no MCS, influenciados por eventos como promoções sazonais e lançamentos de jogos populares.
- Hipótese 3: É possível criar um portfólio de ativos tal que seu retorno seja superior à retenção de 15% do valor da transação cobrado pela plataforma Steam.

# Justificativa

O MCS é uma plataforma única que permite aos jogadores comprar, vender e trocar itens virtuais recebidos em jogos. Houve um expressivo aumento nos preços e nas quantidades das transações desses ativos virtuais, refletindo a crescente popularidade dos videogames e o interesse em possuir e negociar tais itens. O valor estimado do mercado de mais de US$ 15 bilhões ressalta sua importância econômica, tornando-o um objeto de estudo oportuno para a pesquisa acadêmica [@glausSeasonalityIngameItem2022].

Apesar de sua relevância, existem poucas pesquisas acadêmicas sobre a Steam e seu mercado de ativos virtuais. Isso pode ser resultado de diversos elementos, como o conhecimento limitado sobre a indústria de jogos, que vai além da simples compra e venda de jogos; as dificuldades relativamente elevadas para ingressar na plataforma; e a natureza fechada do ambiente, onde os recursos não podem ser retirados ou transferidos para contas externas ou bancos [@glausSeasonalityIngameItem2022].

Portanto, o crescimento do MCS, sua importância econômica e a escassez de pesquisas acadêmicas sobre o assunto fazem dele um tema atraente para investigação. A possibilidade de testar modelos em um ambiente controlado com poucas variáveis a serem consideradas também se mostra interessante, ao contribuir para a redução da complexidade do ambiente de testes para pesquisas aplicadas. A realização de pesquisas nessa área pode fornecer informações valiosas sobre o comportamento do mercado, podendo ser benéfica tanto para pesquisadores como para a comunidade de jogos em geral.

# Metodologia

Para a viabilidade do projeto, é necessário conhecer as regras de compra e venda de ativos virtuais no MCS e, para isso, este trabalho fará uma análise exploratória da página de perguntas mais frequentes do mercado. ^[Disponível em: <https://help.steampowered.com/en/faqs/view/61F0-72B7-9A18-C70B>. Acesso em: 2 ago 2023.] Apesar da plataforma Steam não fornecer em sua API oficial campos específicos para o MCS, os dados sobre os ativos virtuais a serem analisados podem ser acessados pelo site SteamApis ^[Disponível em: <https://steamapis.com/>. Acesso em: 2 ago 2023.] e os dados sobre todas as principais promoções e eventos da loja pelo site SteamDB. ^[Disponível em: <https://steamdb.info/>. Acesso em: 3 ago 2023.] Com o acesso a estes dados, será realizada uma análise descritiva dos principais ativos negociados na plataforma, com informações como volume de negociações, média e volatilidade dos retornos e demais estatísticas descritivas.

O modelo escolhido para o projeto é o LSTM, um tipo de arquitetura de rede neural recorrente (RNN) projetada especificamente para lidar com dependências de longo prazo e sequências de dados. As RNNs são uma classe de redes neurais que podem processar sequências de dados mantendo uma memória interna ou um estado que lhes permite reter informações de etapas de tempo anteriores, sendo natural a aplicação dele para séries temporais [@jamesIntroductionStatisticalLearning2023]. O modelo também considerará os resultados encontrados por @glausSeasonalityIngameItem2022 no que diz respeito ao efeito sazonal das promoções anuais nos preços dos ativos da loja.

Para medir o desempenho do modelo, além do uso de medidas como erro quadrático médio (RMSE) ^[No sentido original, "root mean square error" (tradução nossa).], o projeto utilizará previsão conforme (CP) ^[No sentido original, "conformal prediction" (tradução nossa).], uma técnica de aprendizado de máquina e inferência estatística que fornece uma maneira de quantificar a incerteza associada às previsões utilizando informações anteriores. Diferentemente dos modelos de previsão tradicionais que geram estimativas pontuais, a previsão conforme produz regiões de previsão que contêm o valor verdadeiro com uma probabilidade especificada [@shaferTutorialConformalPrediction2008].

# Revisão bibliográfica

Este trabalho se baseará fundamentalmente nos trabalhos de @glausSeasonalityIngameItem2022 para descrever os efeitos de sazonalidade no MCS; @hanReviewDeepLearning2021, @yuReviewRecurrentNeural2019 e @jamesIntroductionStatisticalLearning2023 para definir e estimar os modelos; @shaferTutorialConformalPrediction2008 e @angelopoulosGentleIntroductionConformal2022 para aplicar a técnica de CP para medir os resultados do modelo.

O trabalho de @glausSeasonalityIngameItem2022 investiga o fenômeno do efeito-promoção no MCS durante o período de dezembro de 2012 a outubro de 2021. ^[Segundo @glausSeasonalityIngameItem2022, o efeito-promoção consiste em uma anomalia de mercado onde os retornos dos itens dos jogos tendem a ser menores em dias no começo e maiores no fim de uma grande promoção na plataforma Steam em relação a dias ondem não existem grandes promoções.] Ao analisar portfólios compostos por itens de oito jogos populares frequentemente negociados no mercado, o estudo encontrou uma forte presença de sazonalidade nos retornos dos itens. Além disso, as medidas de liquidez são examinadas para entender os fatores que contribuem para o surgimento do efeito-promoção. O artigo também explora a eficácia das estratégias de investimento criadas para capitalizar no efeito-promoção, considerando os custos de negociação e seu impacto sobre a lucratividade. Os resultados revelam um efeito-promoção significativo em toda a amostra agregada e nos portfólios de jogos individuais. Esse efeito demonstra que os retornos durante os períodos de promoção exibem um padrão de retornos iniciais mais baixos, seguidos de retornos mais altos no final e após o período de promoção, em comparação com os dias sem promoção. Esse padrão se mantém para a maioria dos portfólios, e a força do efeito-promoção varia entre portfólios ponderados por igual e ponderados por preço, indicando que ele é influenciado pelo valor dos itens. O estudo estabelece que o efeito-promoção não é impulsionado apenas por promoções sazonais individuais específicas, mas sim pela combinação das promoções de verão, outono e inverno. Além disso, um exame das medidas de liquidez sugere que o efeito de promoção pode ser impulsionado pelo aumento do volume de negociação nos dias de promoção. Este artigo contribui para este trabalho por mostrar que tal efeito deve ser incorporado nas estimações de retornos do modelo escolhido. Porém, o estudo conclui que a implementação de estratégias de negociação com base no efeito-promoção é desafiadora devido aos custos substanciais de negociação, que impedem que essas estratégias superem o desempenho de uma estratégia simples de comprar e manter.

Os trabalhos de @shaferTutorialConformalPrediction2008 e @angelopoulosGentleIntroductionConformal2022 definem a técnica de CP. Os chamados "modelos de aprendizado de máquina de caixa-preta" já estão difundidos nas suas mais diversas aplicações. Porém, medidas robustas para quantificar a incerteza dos modelos ainda não são tão comuns, apesar de poderem evitar falhas consideráveis na aplicação dos modelos. A técnica de predição conforme é um paradigma amigável para criar intervalos de incerteza estatisticamente robustos para a predição de tais tipos de modelos. Tal método independe de distribuições no sentido de que possuem garantias explícitas e não assintóticas, mesmo sem nenhuma suposição dos modelos utilizados. Assim, tal técnica se mostra bastante robusta para avaliar o desempenho dos modelos deste trabalho. Por fim, os trabalhos de @hanReviewDeepLearning2021, @yuReviewRecurrentNeural2019 e @jamesIntroductionStatisticalLearning2023 trazem uma visão geral e alguns fundamentos sobre métodos de aprendizado de máquina, além de mostrarem a definição e a aplicação de modelos de RNN, a família de modelos a qual o modelo escolhido por esse trabalho, LSTM, faz parte.

# Cronograma

```{=tex}
\input{./quarto/tex/planning.tex}
```

# Referências

```{=tex}
\referenceStyle
```

::: {#refs}
:::
